import {StyleSheet, Dimensions} from 'react-native';

export const globalStyles = StyleSheet.create({
  addPostButton: {
    backgroundColor: 'white',
    borderColor: 'purple',
    borderRadius: 15,
    borderWidth: 3,
    paddingVertical: 8,
    width: '60%',
  },
  addPostContainer: {
    alignItems: 'center',
    paddingBottom: 10,
    paddingTop: 20,
  },
  addThreadButtonContainer: {
    alignItems: 'center',
    marginVertical: 10,
  },
  addThreadContainer: {
    marginHorizontal: 10,
    marginTop: 12,
  },
  authenticationContainer: {
    paddingHorizontal: 15,
    paddingTop: 40,
  },
  authenticationButtonContainer: {
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 15,
  },
  communityButton: {
    backgroundColor: 'purple',
    borderColor: 'purple',
    borderRadius: 20,
    borderWidth: 2,
    marginBottom: 15,
    paddingVertical: 10,
    width: '85%',
  },
  coursesButton: {
    alignItems: 'center',
    borderColor: 'purple',
    borderRadius: 10,
    borderWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-around',
    margin: 10,
    padding: 10,
    width: '95%',
  },
  communityContainer: {
    alignItems: 'center',
    paddingTop: 20,
  },
  coursesImage: {
    height: 100,
    marginVertical: 10,
    width: 185,
  },
  error: {
    color: 'red',
    fontWeight: 'bold',
    marginBottom: 8,
    marginTop: 3,
    textAlign: 'center',
    fontSize: 18,
  },
  forgotPassword: {
    marginTop: 15,
  },
  forgotPasswordText: {
    color: 'purple',
    fontSize: 18,
    fontWeight: 'bold',
  },
  iconMargin: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  iconMarginCommunity: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  label: {
    color: 'purple',
    fontSize: 18,
    fontWeight: 'bold',
    marginHorizontal: 1,
    marginBottom: 4,
  },
  logoLoginContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 68,
  },
  logoTag: {
    color: 'purple',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 60,
    marginTop: 10,
  },
  noPostText: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  noThreadText: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  placeholderText: {
    fontSize: 18,
    fontWeight: 'bold',
    borderBottomColor: 'purple',
    borderBottomWidth: 3,
  },
  purpleButton: {
    backgroundColor: 'purple',
    borderColor: 'purple',
    borderRadius: 25,
    borderWidth: 2,
    marginBottom: 15,
    paddingVertical: 10,
    width: '60%',
  },
  purpleButtonText: {
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
  },
  screenContainer: {
    alignItems: 'center',
    backgroundColor: 'white',
    flex: 1,
    paddingVertical: 20,
  },
  settingsButton: {
    borderColor: 'purple',
    borderRadius: 10,
    borderWidth: 2,
    margin: 10,
    padding: 10,
    width: '70%',
  },
  settingsButtonContainer: {
    alignItems: 'center',
    paddingBottom: 0,
  },
  threadButton: {
    borderColor: 'purple',
    borderRadius: 12,
    borderWidth: 2,
    marginVertical: 5,
    padding: 10,
    width: '90%',
  },
  threadButtonText: {
    color: 'purple',
    fontSize: 18,
    textAlign: 'center',
  },
  settingsContainer: {
    marginHorizontal: 10,
    marginTop: 12,
  },
  viewThreadContainer: {
    backgroundColor: 'white',
    borderRadius: 5,
    borderWidth: 1,
    margin: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  whiteButton: {
    backgroundColor: 'white',
    borderColor: 'purple',
    borderRadius: 25,
    borderWidth: 2,
    paddingVertical: 10,
    width: '60%',
  },
  whiteButtonText: {
    color: 'purple',
    fontSize: 18,
    textAlign: 'center',
  },
});
